version: '3.0'
services:
  postgres:
    image: ${REVDEBUG_DOCKER_HUB_REGISTRY:-}postgres:11-alpine
    shm_size: ${REVDEBUG_POSTGRES_SHM_SIZE:-256mb}
    volumes:
        - ${REVDEBUG_VOLUME_PATH:-/var/revdebug/server/repo}/revdebug_database:/var/lib/postgresql/data
        - ./init-scripts/postgres:/docker-entrypoint-initdb.d:ro
    environment:
            POSTGRES_USER: ${REVDEBUG_POSTGRES_USER:-rdb_user}
            POSTGRES_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            POSTGRES_DB: ${REVDEBUG_POSTGRES_DATABASE:-revdebug_db}
  devops:
    image: ${REVDEBUG_DOCKER_REGISTRY:-docker3.revdebug.com/}devops:${REVDEBUG_DOCKER_TAG:-latest}
    volumes:
        - interop:/interop
        - ${REVDEBUG_VOLUME_PATH:-/var/revdebug/server/repo}:/app/RevDeBug
        - ${REVDEBUG_VOLUME_PATH:-/var/revdebug/server/git_hive}:/var/RevDeBug/git_hive
        - ${REVDEBUG_VOLUME_CAPATH:-/var/revdebug/ca}:/usr/local/share/ca-certificates:ro
        - ${REVDEBUG_VOLUME_GIT_SSH_KEYS:-/var/revdebug/git-ssh-key-dir}:/git-ssh-key-dir
    environment:
            REVDEBUG_POSTGRES_SERVER: ${REVDEBUG_POSTGRES_SERVER:-postgres}
            REVDEBUG_POSTGRES_PORT: ${REVDEBUG_POSTGRES_PORT:-5432}
            REVDEBUG_POSTGRES_USER: ${REVDEBUG_POSTGRES_USER:-rdb_user}
            REVDEBUG_POSTGRES_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            REVDEBUG_POSTGRES_DATABASE: ${REVDEBUG_POSTGRES_DATABASE:-revdebug_db}
            REVDEBUG_AUTH_OPENID_ADDRESS: ${REVDEBUG_AUTH_OPENID_ADDRESS:-}
            REVDEBUG_AUTH_OPENID_CLIENTID: ${REVDEBUG_AUTH_OPENID_CLIENTID:-DevOps}
            REVDEBUG_AUTH_OPENID_SECRET: ${REVDEBUG_AUTH_OPENID_SECRET:-change_me_in_env_file}
  apm-oap:
    image: ${REVDEBUG_DOCKER_REGISTRY:-docker3.revdebug.com/}apm-oap:${REVDEBUG_DOCKER_TAG:-latest}
    volumes:
        - interop:/interop
    environment:
            SW_STORAGE: postgres
            SW_DATA_SOURCE_USER: ${REVDEBUG_POSTGRES_USER:-rdb_user}
            SW_DATA_SOURCE_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            SW_DATA_SOURCE_SERVER_NAME: ${REVDEBUG_POSTGRES_SERVER:-postgres}
            SW_DATA_SOURCE_PORT_NUMBER: ${REVDEBUG_POSTGRES_PORT:-5432}
            SW_DATA_SOURCE_DATABASE: ${REVDEBUG_POSTGRES_DATABASE:-revdebug_db}
            SW_DATA_SOURCE_STRING_TYPE: varchar
            SW_CORE_METRICS_DATA_TTL: ${SW_CORE_METRICS_DATA_TTL:-14}
            SW_CORE_RECORD_DATA_TTL: ${SW_CORE_RECORD_DATA_TTL:-7}
  apm-ui:
    image: ${REVDEBUG_DOCKER_REGISTRY:-docker3.revdebug.com/}apm-ui:${REVDEBUG_DOCKER_TAG:-latest}
    volumes:
        - interop:/interop
    environment:
            SW_OAP_ADDRESS: oap.apm:12800
            SERVER_maxHttpHeaderSize: 640000
    depends_on:
        - apm-oap
    links:
        - "apm-oap:oap.apm"
  wsproxy:
    image: ${REVDEBUG_DOCKER_REGISTRY:-docker3.revdebug.com/}wsproxy:latest
    environment:
            WSPROXY_CONNECT_HOST: devops
            WSPROXY_APM_HOST: oap.apm
    links:
        - "apm-oap:oap.apm"
        - "devops:devops"
  nginx:
    image: ${REVDEBUG_DOCKER_REGISTRY:-docker3.revdebug.com/}nginx:${REVDEBUG_DOCKER_TAG:-latest}
    ports:
        - "80:80"
        - "443:443"
        - "${REVDEBUG_SERVER_GRPC_PORT:-11800}:11800"
        - "${REVDEBUG_RECORDERS_PORT:-42733}:42733"
        - "${REVDEBUG_APPLICATIONS_PORT:-42734}:42734"
        - "${REVDEBUG_GRPC_PORT:-42735}:42735"
    volumes:
      - interop:/interop
      - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}/nginx:/var/log/nginx
      - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}/certbot/conf:/etc/letsencrypt
      - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}/certbot/www:/var/www/certbot
      - ${REVDEBUG_CERTIFICATE_PATH:-/var/revdebug/cert}:/ssl
      - ${REVDEBUG_UAC_FILE:-./uac}:/uac:ro
    environment:
        APM_AS_DEFAULT: ${REVDEBUG_APM_AS_DEFAULT:-true}
        CERTIFICATE_NAME: ${REVDEBUG_CERTIFICATE_NAME:-}
        KEEP_ACCESS_LOGS: ${REVDEBUG_KEEP_ACCESS_LOGS:-false}
        SERVER_NAME: ${REVDEBUG_SERVER_NAME:-}
        SSL_CERT_PATH: ${REVDEBUG_SSL_CERT_PATH:-}
        SSL_CERTKEY_PATH: ${REVDEBUG_SSL_CERTKEY_PATH:-}
    depends_on:
        - apm-ui
        - apm-oap
        - devops
    links:
        - "apm-oap:oap.apm"
        - "apm-ui:ui.apm"
  mediainit:
    image: ${REVDEBUG_DOCKER_HUB_REGISTRY}alpine
    entrypoint: 
        - /bin/sh
        - -c 
        - "mkdir -p /var/revdebug/keycloak ; chown -R 1000: /var/revdebug/keycloak"
    container_name: mediainit
    restart: "no"
    volumes: 
        - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}:/var/revdebug  
  keycloak:
    image: ${REVDEBUG_DOCKER_REGISTRY:-docker3.revdebug.com/}keycloak:${REVDEBUG_DOCKER_TAG:-latest}
    depends_on:
        - mediainit
    volumes:
        - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}/keycloak:/var/keycloak-config/cfg  
    environment:
            REVDEBUG_CERTIFICATE_NAME: ${REVDEBUG_CERTIFICATE_NAME:-}
            REVDEBUG_SERVER_NAME: ${REVDEBUG_SERVER_NAME:-}
            REVDEBUG_AUTH_OPENID_SECRET: ${REVDEBUG_AUTH_OPENID_SECRET:-}
            KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-change_me_in_env_file}
            DB_USER: ${REVDEBUG_POSTGRES_USER:-rdb_user}
            DB_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            DB_ADDR: ${REVDEBUG_POSTGRES_SERVER:-postgres}
            PROXY_ADDRESS_FORWARDING: "true"
            KEYCLOAK_IMPORT: "true"
volumes:
  interop:
