# Optional certbot image for automatic SSL certificate renewal.
# 
version: '3.0'
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}/certbot/conf:/etc/letsencrypt
      - ${REVDEBUG_ROOTVOLUME_PATH:-/var/revdebug}/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
